apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: hellodevoteam
    name: hellodevoteam
  spec:
    nodeSelector: 
      "node-role.kubernetes.io/infra": "true"
    output:
      to:
        kind: ImageStreamTag
        name: hellodevoteam:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/brobaldv/rhtd2020-build01.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.1
          namespace: openshift
      type: Source
    triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
