apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: hellodevoteam
    name: hellodevoteam
  spec:
    nodeSelector: 
      "node-role.kubernetes.io/infra": "true"
    output:
      to:
        kind: ImageStreamTag
        name: hellodevoteam:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: http://git.brobald.home/Vincentb/WebHelloDevoteam.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.1
          namespace: openshift
      type: Source
    triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: ba7b9c196a7917b4
      type: Generic
    - github:
        secret: 8d1fbff9a18f0e2d
      type: GitHub
  status:
    lastVersion: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
